USE customer_behavior;

-- 1. Data quality check
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT customer_id) AS unique_customers,
    SUM(CASE WHEN purchase_amount IS NULL THEN 1 ELSE 0 END) AS missing_purchase_amount,
    SUM(CASE WHEN review_rating IS NULL THEN 1 ELSE 0 END) AS missing_review_rating
FROM customer_data;

-- 2. Executive revenue snapshot
SELECT
    COUNT(DISTINCT customer_id) AS customers,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer_data;

-- 3. Revenue generated by male vs. female customers
SELECT
    gender,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(100 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER (), 2) AS revenue_share_pct
FROM customer_data
GROUP BY gender
ORDER BY revenue DESC;

-- 4. Category revenue ranking with window functions
SELECT
    category,
    SUM(purchase_amount) AS revenue,
    COUNT(*) AS orders,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    RANK() OVER (ORDER BY SUM(purchase_amount) DESC) AS revenue_rank,
    ROUND(100 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER (), 2) AS revenue_share_pct
FROM customer_data
GROUP BY category
ORDER BY revenue_rank;

-- 5. Top item inside every category
WITH item_revenue AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS orders,
        SUM(purchase_amount) AS revenue,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY SUM(purchase_amount) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    orders,
    revenue
FROM item_revenue
WHERE item_rank = 1
ORDER BY revenue DESC;

-- 6. RFM segmentation using purchase frequency, previous purchases, and monetary value
WITH rfm_base AS (
    SELECT
        customer_id,
        gender,
        category,
        purchase_amount,
        previous_purchases,
        purchase_frequency_days,
        NTILE(4) OVER (ORDER BY purchase_frequency_days DESC) AS recency_score,
        NTILE(4) OVER (ORDER BY previous_purchases ASC) AS frequency_score,
        NTILE(4) OVER (ORDER BY purchase_amount ASC) AS monetary_score
    FROM customer_data
),
rfm_scored AS (
    SELECT
        *,
        recency_score + frequency_score + monetary_score AS rfm_score,
        CASE
            WHEN recency_score + frequency_score + monetary_score >= 10 THEN 'Champions'
            WHEN recency_score + frequency_score + monetary_score BETWEEN 8 AND 9 THEN 'Loyal Growth'
            WHEN recency_score + frequency_score + monetary_score BETWEEN 6 AND 7 THEN 'At Risk'
            ELSE 'Low Engagement'
        END AS rfm_segment
    FROM rfm_base
)
SELECT
    rfm_segment,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases
FROM rfm_scored
GROUP BY rfm_segment
ORDER BY revenue DESC;

-- 7. Estimated CLV proxy by segment
WITH clv_base AS (
    SELECT
        customer_id,
        gender,
        age_group,
        category,
        purchase_amount,
        previous_purchases,
        purchase_frequency_days,
        ROUND(365 / purchase_frequency_days, 2) AS estimated_annual_orders,
        ROUND(purchase_amount * (previous_purchases + (365 / purchase_frequency_days)), 2) AS estimated_clv
    FROM customer_data
)
SELECT
    age_group,
    gender,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS current_revenue,
    ROUND(AVG(estimated_clv), 2) AS avg_estimated_clv,
    RANK() OVER (ORDER BY AVG(estimated_clv) DESC) AS clv_rank
FROM clv_base
GROUP BY age_group, gender
ORDER BY clv_rank;

-- 8. Discount impact analysis
SELECT
    discount_applied,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer_data
GROUP BY discount_applied
ORDER BY revenue DESC;

-- 9. Churn risk proxy: non-subscribers with low frequency and lower prior purchase history
WITH ordered_purchases AS (
    SELECT
        previous_purchases,
        ROW_NUMBER() OVER (ORDER BY previous_purchases) AS row_num,
        COUNT(*) OVER () AS total_rows
    FROM customer_data
),
customer_thresholds AS (
    SELECT
        AVG(previous_purchases) AS median_previous_purchases
    FROM ordered_purchases
    WHERE row_num IN (
        FLOOR((total_rows + 1) / 2),
        CEIL((total_rows + 1) / 2)
    )
),
churn_scored AS (
    SELECT
        c.*,
        CASE
            WHEN c.subscription_status = 'No'
             AND c.purchase_frequency_days >= 90
             AND c.previous_purchases <= t.median_previous_purchases
            THEN 1 ELSE 0
        END AS churn_risk_flag
    FROM customer_data c
    CROSS JOIN customer_thresholds t
)
SELECT
    churn_risk_flag,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue_at_risk,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM churn_scored
GROUP BY churn_risk_flag;

-- 10. Cohort-style behavior by age group and purchase frequency
SELECT
    age_group,
    frequency_of_purchases,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer_data
GROUP BY age_group, frequency_of_purchases
ORDER BY age_group, revenue DESC;

-- 11. Seasonal performance by category
SELECT
    season,
    category,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    DENSE_RANK() OVER (
        PARTITION BY season
        ORDER BY SUM(purchase_amount) DESC
    ) AS category_rank_in_season
FROM customer_data
GROUP BY season, category
ORDER BY season, category_rank_in_season;

-- 12. State/location revenue leaderboard
SELECT
    location,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    RANK() OVER (ORDER BY SUM(purchase_amount) DESC) AS location_revenue_rank
FROM customer_data
GROUP BY location
ORDER BY location_revenue_rank
LIMIT 10;

-- 13. Payment method behavior
SELECT
    payment_method,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases
FROM customer_data
GROUP BY payment_method
ORDER BY revenue DESC;

-- 14. Subscription opportunity: non-subscribers with strong purchase history
SELECT
    customer_id,
    gender,
    age_group,
    category,
    purchase_amount,
    previous_purchases,
    frequency_of_purchases,
    ROUND(purchase_amount * (previous_purchases + (365 / purchase_frequency_days)), 2) AS estimated_clv
FROM customer_data
WHERE subscription_status = 'No'
  AND previous_purchases >= 38
ORDER BY estimated_clv DESC
LIMIT 25;
